defaults:
  - _self_  # all below configs will override this conf.yaml
  - task: visual_manipulation

vima_bench_kwargs:
  task_name: ???
  task_kwargs: 
    camera_rotation: [0.0, -0.383, 0.0, 0.924] # Approx -45 deg pitch
    camera_position: [0.0, 0.0, 0.0]
  modalities: ["rgb", "segm"]
  seed: 42
  debug: false
  display_debug_window: true
  render_prompt: true
  hide_arm_rgb: false

hydra:
  run:
    dir: .
  output_subdir: null

inference_model:
  _target_: inference.gemini.GeminiInference
  model_path: gemini-2.0-flash
  plan_strategy:
    _target_: inference.plan.VimaPlan
  verifier_strategy:
    _target_: inference.verifier.TwoStepVerification    

state_1_image_path: /home/hice1/che321/scratch/VLM/vima-perturb-cleaned/images/state_s1_6.png
state_2_image_path: /home/hice1/che321/scratch/VLM/vima-perturb-cleaned/images/state_s2_6.png
max_perturb_steps: 1
